<div>
    <label>
        Имя *
        <input type="text" name="post[name]" value="<?= htmlspecialchars($post['name'] ?? '') ?>">
    </label>
    <?php if (isset($errors['name'])): ?>
        <div style='display:inline';><?= $errors['name'] ?></div>
    <?php endif ?>
</div>
<div>
    <label>
        Содержимое *
    </label>
    <textarea type="text" rows="20" cols="80" name="post[body]"><?= $post['body'] ?? '' ?></textarea>
    <?php if (isset($errors['body'])): ?>
        <div style='display:inline';><?= $errors['body'] ?></div>
    <?php endif ?>
</div>
