<a href="<?= $router->urlFor('newPost') ?>">Новый пост</a>
<br>
<?php
foreach ($posts as $post) :
    $postLink = "{$router->urlFor('posts')}/{$post['id']}";
    $postName = htmlspecialchars($post['name']);
    echo "{$post['number']} - <a href='{$postLink}'>{$postName}</a>" . '<br>';
endforeach; ?>
<br>

<form method='get'>
    <button name='page' value='<?= $page - 1 ?>'>Назад</button>
    <button name='page' value='<?= $page + 1 ?>'>Вперёд</button>
</form>
<br>
<div style="color:green">
    <?php foreach ($messages['success'] as $message) :
        echo $message;
    endforeach; ?>
</div>