<a href="/posts">Посты</a>
<form action='/posts' method="post">
  <!-- Name<input type="text" value="<?= htmlspecialchars($post['name']) ?? '' ?>" name="post[name]"><?= $errors['name'] ?>
  <br>
  Body<input type="text" value="<?= htmlspecialchars($post['body']) ?? '' ?>" name="post[body]">  <?= $errors['body'] ?>
  <br> -->
  <?php require '_form.phtml' ?>
  <input type="submit" value="Create">
</form>