<a href=<?= $router->urlFor('users') ?>>Пользователи</a>

<style>
  table {
    font-size: 22px;
  }
  a {
    font-size: 22px;
  }
  td,
  th {
    border: none;
  }
  form {
    width: fit-content;
    display: inline;
  }
</style>

<table>
  <th>Name</th>
  <th>Email</th>
  <th>Id</th>
  <tr>
    <td><?= htmlspecialchars($user->nickname) ?>
    <td><?= htmlspecialchars($user->email) ?>
    <td><?= $user->id ?>
  </tr>
</table>
