<?php require '_showUser.phtml'; ?>

<?php if (!isset($confirm)) { ?>
  <form action="<?= $router->urlFor('editUser', ['id' => $user->id]) ?>">
    <input type="submit" value="Edit user">
  </form>
  <form action="<?= $router->urlFor('user', ['id' => $user->id]) ?>" method="post">
    <input hidden name="_METHOD" value="DELETE">
    <input type="submit" value="Delete user">
  </form>
<?php } else { ?>
  <form action="<?= $router->urlFor('user', ['id' => $user->id]) ?>" method="post">
    <input hidden name="_METHOD" value="DELETE">
    Are you sure?
    <br>
    <button value="1" name='confirm'>Yes</button>
    <button value="0" name='confirm'>No</button>
  </form>
<?php }
